#!/bin/bash
# 批量上传脚本 - 由 github-to-feishu-sync-auto.py 生成
# 生成时间: 2026-04-04T06:11:24.177242
#

echo '[1] 上传: EMA 关于非致突变杂质的界定的思考性文件 Reflection paper on the qualification of non-mutagenic impurities 20260313 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/EMA/EMA 关于非致突变杂质的界定的思考性文件 Reflection paper on the qualification of non-mutagenic impurities 20260313 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[2] 上传: ANDA 申报.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/FDA/ANDA 申报.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[3] 上传: FDA Orange Book - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/FDA/FDA Orange Book - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[4] 上传: M4Q(R1) Quality cn - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/M4Q(R1) Quality cn - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[5] 上传: M7 R2 评估和控制药物中DNA反应性致突变杂质以限制潜在致癌风险 20230403 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/M7 R2 评估和控制药物中DNA反应性致突变杂质以限制潜在致癌风险 20230403 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[6] 上传: M7 R2 问答文件 20220524 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/M7 R2 问答文件 20220524 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[7] 上传: Q11 原料药开发和生产 化学实体和生物技术-生物实体药物 20120501 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q11 原料药开发和生产 化学实体和生物技术-生物实体药物 20120501 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[8] 上传: Q11 问答 原料药开发和生产 化学实体和生物技术-生物实体药物 问答 20170823 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q11 问答 原料药开发和生产 化学实体和生物技术-生物实体药物 问答 20170823 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[9] 上传: Q13 原料药和制剂的连续制造 20221116 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q13 原料药和制剂的连续制造 20221116 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[10] 上传: Q14 分析方法开发 20231101 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q14 分析方法开发 20231101 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[11] 上传: Q1A R2 新原料药和制剂的稳定性试验 20030206 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q1A R2 新原料药和制剂的稳定性试验 20030206 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[12] 上传: Q1B 稳定性试验新原料药和制剂的光稳定性试验 19961106 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q1B 稳定性试验新原料药和制剂的光稳定性试验 19961106 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[13] 上传: Q1指导原则草案 20250506 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q1指导原则草案 20250506 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[14] 上传: Q2 R2 分析方法验证 20231101 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q2 R2 分析方法验证 20231101 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[15] 上传: Q3A R2 新原料药中的杂质 20061025 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q3A R2 新原料药中的杂质 20061025 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[16] 上传: Q3C R9 杂质残留溶剂的指导原则 20240124 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q3C R9 杂质残留溶剂的指导原则 20240124 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[17] 上传: Q3D R2 元素杂质指导原则 20220426 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q3D R2 元素杂质指导原则 20220426 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[18] 上传: Q3E 指导原则草案 20250926 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q3E 指导原则草案 20250926 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[19] 上传: Q7 原料药的药品生产质量管理规范指南 20001110 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q7 原料药的药品生产质量管理规范指南 20001110 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[20] 上传: Q7 问答 原料药的药品生产质量管理规范指南问答 20150610 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q7 问答 原料药的药品生产质量管理规范指南问答 20150610 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[21] 上传: Q8 R2 药品研发 200908 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/ICH/Q8 R2 药品研发 200908 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[22] 上传: CDE 创新药化学药临床试验期间药学变更技术指导原则试行 20210303 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/CDE 创新药化学药临床试验期间药学变更技术指导原则试行 20210303 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[23] 上传: CDE 已上市化学药品药学变更研究技术指导原则试行 20210210 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/CDE 已上市化学药品药学变更研究技术指导原则试行 20210210 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[24] 上传: CFDI 工艺验证检查指南 20250407 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/CFDI 工艺验证检查指南 20250407 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[25] 上传: CFDI 药品注册核查工作程序试行 20211217 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/CFDI 药品注册核查工作程序试行 20211217 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[26] 上传: CFDI 药品注册核查要点与判定原则药学研制和生产现场试行 20211217 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/CFDI 药品注册核查要点与判定原则药学研制和生产现场试行 20211217 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[27] 上传: NMPA 化学药品注册分类及申报资料要求 20200629 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/NMPA 化学药品注册分类及申报资料要求 20200629 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[28] 上传: NMPA 药品记录与数据管理要求试行 20200624 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/NMPA 药品记录与数据管理要求试行 20200624 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[29] 上传: SAMR 药品注册管理办法 20200122 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/SAMR 药品注册管理办法 20200122 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[30] 上传: 广东省药品注册研发质量管理指南（征求意见稿）康利华解读 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/NMPA CFDA CFDI/广东省药品注册研发质量管理指南（征求意见稿）康利华解读 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[31] 上传: 分类基因毒性杂质 - 识林 1.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/研究专题/分类基因毒性杂质 - 识林 1.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[32] 上传: 分类研发质量体系 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/研究专题/分类研发质量体系 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '[33] 上传: 分类警示结构 - 识林.md'
feishu_drive_file action=upload file_path='/home/node/.openclaw/workspace/KB-backup/KB/研究专题/分类警示结构 - 识林.md' folder_token='Ofu0fS87fl5SHwdTZSmcmXoQnse'
echo ''
echo '批量上传完成'
